import { Lora } from "next/font/google"; // Import Lora font
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const lora = Lora({
  variable: "--font-lora", // Custom variable name for the font
  subsets: ["latin"],
  weight: ["400", "700"], // Choose the font weights you need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lora.variable} antialiased`} // Apply the Lora font here
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
